name: eeblog
version: 1

handle:
- rewrite:if(!is_dir()&&!is_file()) goto "index.php?%{QUERY_STRING}"
- expire: if( path ~ "css" ) time 864000
- expire: if( path ~ "png" ) time 864000
- expire: if( path ~ "js" ) time 864000
- expire: if( path ~ "jpg" ) time 864000
- compress: if ( out_header["Content-Length"]>=512 ) compress